include: package:lints/recommended.yaml
analyzer:
  language:
    strict-raw-types: true
    strict-inference: true
    strict-casts: true
linter:
  rules:
    always_declare_return_types: true
    prefer_single_quotes: true
    unawaited_futures: true
    package_api_docs: true
    public_member_api_docs: true
    type_annotate_public_apis: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
