name: math_parser
description: Process math expressions, like formulas or parts of equations, convert them to machine-readable 
  form, and calculate them. 
version: 1.4.0
homepage: https://github.com/Sominemo/Math-Parser-Dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
